"""empty message

Revision ID: 0aaf50e01c8e
Revises: 927b1ebfdfe7
Create Date: 2024-07-09 04:05:30.200304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaf50e01c8e'
down_revision = '927b1ebfdfe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chambre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chambre', schema=None) as batch_op:
        batch_op.drop_column('classe')

    # ### end Alembic commands ###
