"""empty message

Revision ID: 927b1ebfdfe7
Revises: ceba231af8bd
Create Date: 2024-07-09 02:43:52.649070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927b1ebfdfe7'
down_revision = 'ceba231af8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chambre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_debut', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambre.id'], name='reservation_chambre_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_register.id'], name='reservation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    # ### end Alembic commands ###
